name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        brew install tesseract
        brew install poppler
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Verify required files
      run: |
        echo "Checking required files:"
        ls -la scrapey.spec
        ls -la resources/scrapey.icns
        ls -la scrapey/main.py
        ls -la scrapey/settings.ini
    
    - name: Clean previous builds
      run: |
        rm -rf build dist
        mkdir -p dist
    
    - name: Build application
      run: |
        echo "Building with basic PyInstaller command first:"
        pyinstaller --clean --noconfirm scrapey/main.py --name scrapey --windowed --icon resources/scrapey.icns
        
        echo "If basic build succeeds, try full spec file:"
        pyinstaller --clean --noconfirm scrapey.spec
        
        echo "Contents of dist directory:"
        ls -la dist/
    
    - name: Verify build output
      run: |
        if [ ! -d "dist/scrapey.app" ]; then
          echo "Error: dist/scrapey.app not found"
          echo "Contents of dist directory:"
          ls -la dist/
          exit 1
        fi
        if [ ! -f "dist/scrapey" ]; then
          echo "Error: dist/scrapey not found"
          echo "Contents of dist directory:"
          ls -la dist/
          exit 1
        fi
    
    - name: Create release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/scrapey.app
          dist/scrapey
        draft: true
        prerelease: false
        tag_name: v1.0.0
        name: Release v1.0.0
        body: |
          Initial release of Scrapey
          
          Features:
          - PDF text extraction
          - OCR support
          - Web page text extraction
          - Modern Qt-based GUI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 